In [63]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [64]:
from sklearn.datasets import load_iris
iris = load_iris()

In [65]:
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
df['target'] = iris.target


In [66]:
print(df)

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  

In [67]:
X = df.iloc[:, :-1].values
y = df.iloc[:, 4].values

In [68]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.40)

In [69]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=8,)
classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=8)

In [70]:
y_pred = classifier.predict(X_test)

In [71]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, y_pred)
print("Classification Report:",)
print (result1)
result2 = accuracy_score(y_test,y_pred)
print("Accuracy:",result2)

Confusion Matrix:
[[22  0  0]
 [ 0 19  2]
 [ 0  1 16]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        22
           1       0.95      0.90      0.93        21
           2       0.89      0.94      0.91        17

    accuracy                           0.95        60
   macro avg       0.95      0.95      0.95        60
weighted avg       0.95      0.95      0.95        60

Accuracy: 0.95


In [74]:
result = classifier.predict([[3, 5, 0.6, 0.6],])

print(iris.target_names[result])

['setosa']
