scikit-learn's __CountVectorizer()__ is used to convert text documents into a vector

cosine_similarity__ of the sci-kit learn is used for the metric of similarity matrix

In [ ]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
df=pd.read_csv("movie_dataset.csv")

<ipython-input-22-5f12553ef275>:1: DtypeWarning: Columns (0,1,4,9,13,14,19,20,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,27

In [ ]:
df.head(5)

index     budget                                    genres  \
0     0  237000000  Action Adventure Fantasy Science Fiction   
1     1  300000000                  Adventure Fantasy Action   
2     2  245000000                    Action Adventure Crime   
3     3  250000000               Action Crime Drama Thriller   
4     4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ...  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   
3  Following the death of District Attorney Harve...   112.31295  ...   
4  John Carter is a war-weary, former military ca...   43.926995  ...   

  Unnamed: 659 Unnamed: 660 Unnamed: 661 Unnamed: 662 Unnamed: 663  \
0          NaN          NaN          NaN          NaN          NaN   
1          NaN          NaN          NaN          NaN          NaN   
2          NaN          NaN          NaN          NaN          NaN   
3          NaN          NaN          NaN          NaN          NaN   
4          NaN          NaN          NaN          NaN          NaN   

  Unnamed: 664 Unnamed: 665 Unnamed: 666 Unnamed: 667 Unnamed: 668  
0          NaN          NaN          NaN          NaN          NaN  
1          NaN          NaN          NaN          NaN          NaN  
2          NaN          NaN          NaN          NaN          NaN  
3          NaN          NaN          NaN          NaN          NaN  
4          NaN          NaN          NaN          NaN          NaN  

[5 rows x 669 columns]

## Features list
We'll choose the features which are most relevant to us i.e. _*keywords, cast, genres, director*_

In [ ]:
features = ['keywords', 'cast', 'genres', 'vote_average']

### removing null values

In [ ]:
for feature in features:
  df[feature] = df[feature].fillna('')

## Combined Features List
combining the relevant features into a single feature

In [ ]:
def combined_features(row):
    return row['keywords']+" "+row['cast']+" "+row['genres']+" "+row['director']

df['combined_features'] = df.apply(combined_features,axis = 1)

## Extracting Features
1. __sklearn.feature_extraction__ module can be used to extract features in format supported by machine learning algorithms
2. __CountVectorizer()'s__ _*fit_transform*_ will help to count the number of text

In [ ]:
cv = CountVectorizer()
count_matrix = cv.fit_transform(df['combined_features'])
print("Count Matrix: ",count_matrix.toarray())

Count Matrix:  [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


## Cosine Similarity
We'll use the cosine_similarity as a metric to compute similarity between two items.

__cosine_sim__ is a numpy array with calculated cosine-similarity between two movies.

In [ ]:
cosine_sim = cosine_similarity(count_matrix)


now we'll take the input movies that user like in the __movie_user_like__ variable.

we need to know the content user like in order to predict the similar.

In [ ]:
movie_user_like = "Dead Poets Society"

def get_index_from(title):
    return df[df.title == title]["index"].values[0]

movie_index = get_index_from(movie_user_like)

## Generating similar movies matrix

In [ ]:
similar_movies = list(enumerate(cosine_sim[movie_index]))

In [ ]:
print(similar_movies)

[(0, 0.0), (1, 0.0), (2, 0.044455422447438706), (3, 0.16724840200141816), (4, 0.0), (5, 0.0), (6, 0.0), (7, 0.0), (8, 0.04545454545454545), (9, 0.0), (10, 0.0), (11, 0.04264014327112209), (12, 0.0), (13, 0.0), (14, 0.04029114820126901), (15, 0.0), (16, 0.0), (17, 0.0), (18, 0.03892494720807614), (19, 0.04545454545454545), (20, 0.04351941398892446), (21, 0.0), (22, 0.04891159880445184), (23, 0.0), (24, 0.03768891807222045), (25, 0.04767312946227961), (26, 0.0), (27, 0.0), (28, 0.0), (29, 0.0), (30, 0.0), (31, 0.0), (32, 0.0), (33, 0.0), (34, 0.04545454545454545), (35, 0.04652421051992354), (36, 0.04351941398892446), (37, 0.0), (38, 0.04181210050035454), (39, 0.0), (40, 0.11877113736973435), (41, 0.04181210050035454), (42, 0.04545454545454545), (43, 0.0), (44, 0.0), (45, 0.04181210050035454), (46, 0.039590379123244784), (47, 0.0), (48, 0.0), (49, 0.04652421051992354), (50, 0.0), (51, 0.08058229640253801), (52, 0.0909090909090909), (53, 0.0), (54, 0.0), (55, 0.0), (56, 0.0), (57, 0.053300

## Sorting the similar movies in descending order

In [ ]:
sorted_similar_movies = sorted(similar_movies, key = lambda x:x[1], reverse = True)

In [ ]:
print(sorted_similar_movies)

[(2453, 0.9999999999999997), (3450, 0.3481553119113957), (592, 0.3302891295379081), (685, 0.28721347895177635), (3642, 0.28603877677367767), (354, 0.2727272727272727), (4165, 0.266500895444513), (2758, 0.25584085962673253), (2638, 0.25087260300212727), (4643, 0.24618298195866548), (1709, 0.23836564731139806), (3709, 0.23262105259961768), (3774, 0.22727272727272724), (887, 0.21759706994462233), (1508, 0.20683507599800763), (3425, 0.20515248496555455), (2741, 0.20145574100634506), (4070, 0.20145574100634506), (757, 0.20100756305184242), (1264, 0.20100756305184242), (2809, 0.20100756305184242), (2350, 0.19564639521780736), (3277, 0.19564639521780736), (3446, 0.19564639521780736), (4434, 0.19564639521780736), (1197, 0.1914598952668709), (853, 0.19069251784911845), (1530, 0.19069251784911845), (1597, 0.19069251784911845), (2776, 0.19069251784911845), (2798, 0.19069251784911845), (3836, 0.19069251784911845), (4141, 0.19069251784911845), (659, 0.18609684207969415), (1013, 0.18609684207969415)

## Printing the  Similar Movies

In [ ]:
def get_title_from_index(index):
    return df[df.index == index]["title"].values[0]

i=0
for movies in sorted_similar_movies:
    print(get_title_from_index(movies[0]))
    i = i+1;
    if i>15:
        break

Wall Street
Platoon
Wall Street: Money Never Sleeps
The American President
Kill the Messenger
The Departed
Northfork
Being John Malkovich
The Clan of the Cave Bear
Amidst the Devil's Wings
The Big Short
Salvador
Talk Radio
Catch Me If You Can
Takers
Boyz n the Hood
